# Site settings
title: Dani Traphagen
email: dtrapezoid@gmail.com
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dtrapezoid
  - title: facebook
    url: https://www.facebook.com/danielle.traphagen
  - title: github
    url: http://github.com/dtrap

# Postal address (add as many lines as necessary)
location:
  - line: San Clemente, CA 92672

# Build settings
markdown: kramdown
permalink: pretty
